version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8005:8000"
    volumes:
      - .:/app
  django:
    build: .
    command: python backend/django_app/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app